theme: jekyll-theme-cayman
url: "https://hshin-git.github.io/GyroM5/"
plugins:
  - jekyll-sitemap
title: ラジコン用ジャイロ"GyroM5"
description: オープンソースとM5StickCで自作するドリフトRCカー用ステアリングジャイロ
locale: ja_JP
languages: ['ja','en']
default_lang: 'ja'
