theme: jekyll-theme-slate
url: "https://hshin-git.github.io/GyroM5/"
plugins:
  - jekyll-sitemap
title: ラジドリ用ジャイロ"GyroM5"
description: M5StickCで自作するオープンソースのラジコン二駆ドリフト用ステアリングジャイロ
locale: ja_JP
languages: ['ja','en']
default_lang: 'ja'
