theme: jekyll-theme-cayman
url: "https://hshin-git.github.io/GyroM5/"
plugins:
  - jekyll-sitemap
title: ラジドリ用の自作ジャイロ"GyroM5"
description: オープンソースとM5StickCで自作するドリフトRCカー用ステアリング補助ジャイロの解説記事
locale: ja_JP
